SELECT TOP (1000) [kId]
      ,[createdAt]
      ,[updatedAt]
      ,[siteNumber]
      ,[systemNumber]
      ,[alarmIncidentNumber]
      ,[dispatchLocation]
      ,[alaramEventId]
      ,[currentWriteEventCode]
      ,[fullClearStatus]
      ,[isActiveAlert]
      ,[alertHandlingStatusCode]
      ,[alertHandlingStatusMessage]
      ,[progressMessages]
      ,[contacts]
      ,[callGeneratedText]
      ,[textToSpeechFileLocation]
      ,[vonageCurrentConversationId]
      ,[answeredPhoneNumber]
      ,[orderOfAnsweredCall]
      ,[vonageConversationLength]
      ,[customerResponseToCall]
  FROM [Generic].[dbo].[Alerts]