SELECT TOP (1000) [conversationId]
      ,[uuid]
      ,[fromNo]
      ,[toNo]
      ,[eventTimestamp]
      ,[disconnectedBy]
      ,[duration]
      ,[rate]
      ,[price]
      ,[startTime]
      ,[endTime]
      ,[rawEvent]
      ,[kId]
  FROM [Generic].[dbo].[Conversations]